<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="it-ThinkCentre-M720q" failures="1" tests="1" name="Validate Title" time="6.18" errors="0" timestamp="2021-07-28T10:24:42 IST">
  <testcase classname="test_Cases.ValidateTitle" name="validateAppTitle" time="0.585">
    <failure type="java.lang.AssertionError" message="expected [TEST] but found [SIGN IN]">
      <![CDATA[java.lang.AssertionError: expected [TEST] but found [SIGN IN]
at test_Cases.ValidateTitle.validateAppTitle(ValidateTitle.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validateAppTitle -->
</testsuite> <!-- Validate Title -->
